### ISSUE TITLE
Support generating HTML from Rmd

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/r-docker#32]
@acagreen17 wants to do something like:

```yaml
flow_chart_all:
    run: r:latest analysis/R/study_definition_all_flow_chart.Rmd
    needs: [generate_flowchartdata]
    outputs:
      moderately_sensitive:
        html: output/study_definition_all_flow_chart.html
```

In other words, for it to be possible to run this docker image in such a way we can convert RMarkdown to HTML. In the first instance we "just" need to add an endpoint to the image that:

* takes Rmd script as its first argument
* takes a relative folder as its second argument (default: `output/`)
* writes the HTML to the output folder

I attempted to support this way back in the day, but hit various dead ends related to me not understanding enough about R.
